# Generated by Django 2.0.2 on 2019-08-14 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='update',
            new_name='updated',
        ),
    ]
